config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get '/' => 'homes#top'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
  end

  def index
    @books = Book.all
    @book = Book.new

  end

  def create
    @books = Book.all.order(id: :asc)
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    book.save
      flash[:notice] = 'Book was successfully destroyed.'
    redirect_to '/books'
  end




  def edit
     @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
    flash[:notice] = 'Book was successfully updated.'
    redirect_to book_path(@book.id)
    else
     render :edit
    end
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookes_helper.rb
module BookesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<div class= "flash">
<%= flash[:notice] %></div>

<header>
    <h1>Editing Book</h1>
</header>

<% if @book.errors.any? %>
    <div class="box-title">
    <p><%= @book.errors.count %>errors prohibited this book from being saved:</p></div>
    <div class="box">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
    <% end %>

<div class="edit">
    <%= form_with model: @book , url: book_path(@book.id), method: :patch do |f| %>


    <h4>Title</h4>
    <%= f.text_field :title %>



    <h4>Body</h4>
    <%= f.text_area :body %>
    <ol>
    <li><%= f.submit 'Update Book' %></li>

    <li><%= link_to 'Show ' , book_path(@book.id) %>|
        <%= link_to 'Back' , '/books' %></li>

    <% end %>
    </ol>


    </div>

app/views/books/index.html.erb
<div class= "flash">
<%= flash[:notice] %></div>

<h1>Books</h1>
<table>
<thead>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
  </tr>
</thead>

<tbody>

  <% @books.each do |book| %>
  <tr>


    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to 'Show' , book_path(book.id) %></td>
    <td><%= link_to 'Edit' , edit_book_path(book.id) %></td>
    <td><%= link_to 'Destroy' , book_path(book.id) , method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>
  
  <% end %>
</tbody>
</table>

<div class="new">
  <ol>
  <li><h2>New book</h2></li>
  
  <% if @book.errors.any? %>
    <div class="box-title">
    <p><%= @book.errors.count %>errors prohibited this book from being saved:</p></div>
    <div class="box">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    
  </div>
  <% end %>


   <%= form_with model: @book do |f| %>


  <li><h4>Title</h4></li>
  <li><%= f.text_field :title %></li>

  <li><h4>Body</h4></li>
  <li><%= f.text_area :body %></li>

  <br><%=f.submit ' Create Book ' %></br>

  <% end %>
  </ol>
</div>

app/views/books/show.html.erb
 <div class= "flash">
  <%= flash[:notice] %></div>
  

  <%= yield %>
 
  <div class="show"><p>Title:
  <%= @book.title %></p>
  <p>Body:
  <%= @book.body %></p>
   </div>
  <div class="show2">
  <p><%= link_to 'Edit' , edit_book_path(@book.id) %></p>|
  <p><%= link_to 'Back' , '/books' %></p>
 
  </div>
  
  
  
 

app/views/homes/top.html.erb
<header>
    <h1>ようこそBookersへ!</h1>
</header>

<main>
    <p>Bookers では、さまざまな書籍に関するあなたの意見や</br>

    印象を共有し交換することができます</p>



   <p><%= link_to 'start' ,books_path %></p> 
    
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=monospace+Sprict" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>